# Config file using the contextual/thompson pattern and providing its parameters
# This configuration causes the bandit to do no logging of its activity

pattern: contextual/thompson
num_actions: 15
context_size: 15

# Number of actions is set to a maximum of 15. This means a maximum of 15 installed skills
# (including a NOOP action) are supported.
# Context size should be equal to the number of actions
